//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.487, BuildCommit: 7236fb639f14df1e38d271aedaa5b59044d3e969)
//
//    - LC_BUILD_VERSION:  
//    - LC_SOURCE_VERSION: 1859.0.0.0.0
//
#ifndef OSISAEAExtractor_h
#define OSISAEAExtractor_h
@import Foundation;

@class NSArray, NSObject, NSString;

@interface OSISAEAExtractor : NSObject

@property (retain, nonatomic) NSString *appleEncryptedArchivePath;
@property (retain, nonatomic) NSString *destinationDirectoryPath;
@property (copy, nonatomic) id /* block */ progressHandler;
@property (nonatomic) struct AAPathFilter_impl * pathFilter;
@property (retain, nonatomic) NSArray *filteredPathsToExtract;

/* instance methods */
- (id)initWithArchivePath:(id)path outputPath:(id)path progressHandler:(id /* block */)handler;
- (void)dealloc;
- (signed char)extractUsingDecryptionKey:(id)key error:(id *)error;
- (signed char)_extractAssetArchiveFromDecryptionStream:(struct AAByteStream_impl *)stream outError:(id *)error;
- (signed char)_extractAssetArchiveFromDecryptionStream:(struct AAByteStream_impl *)stream pathFilter:(struct AAPathFilter_impl *)filter outError:(id *)error;

@end

#endif /* OSISAEAExtractor_h */
